In [1]:
import pandas as pd
from descompacta import descompactar_arquivos

In [2]:
descompactar_arquivos()

In [3]:
df1 = pd.read_csv('data/1T2025.csv', sep=';')
df2 = pd.read_csv('data/2T2025.csv', sep=';')
df3 = pd.read_csv('data/3T2025.csv', sep=';')

In [ ]:
display(df1.head())
display(df2.head())
display(df3.head())

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-01-01,316458,46411,PUBLICIDADE E PROPAGANDA,0,1070
1,2025-01-01,316458,464119,Publicidade e Propaganda,0,1070
2,2025-01-01,316458,46411901,Publicidade e Propaganda,0,1070
3,2025-01-01,316458,464119011,Publicidade e Propaganda,0,1070
4,2025-01-01,316458,465,DESPESAS COM TRIBUTOS,0,"99024,72"

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-04-01,421723,452119014,Juros - PESL,0,0
1,2025-04-01,421723,452119015,Variação cambial - PESL,0,0
2,2025-04-01,421723,452119019,Outras,0,0
3,2025-04-01,421723,45212,DESPESAS FINANCEIRAS COM OPERAÇÕES DE ASSISTÊN...,0,0
4,2025-04-01,421723,452129,Despesas Financeiras com Operações de Assistên...,0,0

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-07-01,344800,35,RECEITAS FINANCEIRAS,"3094590,67","4212815,67"
1,2025-07-01,344800,351,RECEITAS DE APLICAÇÕES FINANCEIRAS,"1222303,16","1953149,18"
2,2025-07-01,344800,3511,RECEITAS COM TÍTULOS DE RENDA FIXA PRIVADOS,"1222303,16","1953149,18"
3,2025-07-01,344800,35111,RECEITAS COM DEPÓSITOS BANCÁRIOS A PRAZO - CDB...,0,0
4,2025-07-01,344800,351119,Receitas com Depósitos Bancários a Prazo - CDB...,0,0