In [16]:
import sys
import os

scripts_path = os.path.abspath(os.path.join(os.getcwd(), '..', 'scripts'))
if scripts_path not in sys.path:
    sys.path.insert(0, scripts_path)

In [17]:
# TESTES 1 e 2 - TRADE-OFFS no README.md

In [18]:
import pandas as pd
from api_requests import baixar_e_descompactar

In [19]:
from api_requests import baixar_e_descompactar

api_url = [
    'https://dadosabertos.ans.gov.br/FTP/PDA/demonstracoes_contabeis/2025/1T2025.zip',
    'https://dadosabertos.ans.gov.br/FTP/PDA/demonstracoes_contabeis/2025/2T2025.zip',
    'https://dadosabertos.ans.gov.br/FTP/PDA/demonstracoes_contabeis/2025/3T2025.zip',
    #'https://dadosabertos.ans.gov.br/FTP/PDA/operadoras_acreditadas/operadoras_acreditadas.csv',
    'https://dadosabertos.ans.gov.br/FTP/PDA/operadoras_de_plano_de_saude_ativas/Relatorio_cadop.csv',
    'https://dadosabertos.ans.gov.br/FTP/PDA/operadoras_de_plano_de_saude_canceladas/Relatorio_cadop_canceladas.csv',
    #'https://dadosabertos.ans.gov.br/FTP/PDA/operadoras_e_prestadores_nao_hospitalares/operadoras_e_prestadores_nao_hospitalares.zip'
]

baixar_e_descompactar(api_url)

Baixando 1T2025.zip...
Descompactando 1T2025.zip
Baixando 2T2025.zip...
Descompactando 2T2025.zip
Baixando 3T2025.zip...
Descompactando 3T2025.zip
Baixando Relatorio_cadop.csv...
Baixando Relatorio_cadop_canceladas.csv...

In [20]:
import pandas as pd
import os

DATA_DIR = os.path.join('..', 'data')

#apenas arquivos dos trimestres
paths = [
    os.path.join(DATA_DIR, f)
    for f in os.listdir(DATA_DIR)
    if f.endswith(".csv") and f.startswith(("1T", "2T", "3T"))
]

def le_exibe_colunas(path):
    chunk = next(pd.read_csv(path, sep=';', encoding='utf-8', chunksize=100_000))
    print(chunk.columns.tolist())
    
    
for path in paths:
    print(f"\nArquivo: {path}")
    le_exibe_colunas(path)

def trimestre_filtrados(path, valor, coluna='DESCRICAO'):
    for chunk in pd.read_csv(path, sep=';', encoding='utf-8', chunksize=100_000):
        mask = (
            chunk[coluna]
            .astype(str)
            .str.strip()
            .str.upper()
            .str.contains(valor.upper(), na=False, regex=True)
        )
        if mask.any():
            yield chunk.loc[mask]
            
df_eventos = pd.concat(
    (
        chunk
        for path in paths
        for chunk in trimestre_filtrados(path, r'(?=.*EVENT)(?=.*SINISTR)')
    ),
    ignore_index=True
)

df_eventos.head()

Arquivo: ../data/1T2025.csv
['DATA', 'REG_ANS', 'CD_CONTA_CONTABIL', 'DESCRICAO', 'VL_SALDO_INICIAL', 'VL_SALDO_FINAL']

Arquivo: ../data/2T2025.csv
['DATA', 'REG_ANS', 'CD_CONTA_CONTABIL', 'DESCRICAO', 'VL_SALDO_INICIAL', 'VL_SALDO_FINAL']

Arquivo: ../data/3T2025.csv
['DATA', 'REG_ANS', 'CD_CONTA_CONTABIL', 'DESCRICAO', 'VL_SALDO_INICIAL', 'VL_SALDO_FINAL']

,DATA,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL
0,2025-01-01,316849,131719011,Depósitos Judiciais - Eventos / Sinistros,"289349,17","292907,23"
1,2025-01-01,316849,21111203,Provisão de Eventos/Sinistros a Liquidar para ...,0,0
2,2025-01-01,316849,23111202,Provisão de Eventos/Sinistros a Liquidar para ...,"203169,04","199868,05"
3,2025-01-01,316849,231112022,Provisão de Eventos/Sinistros a Liquidar para ...,"203169,04","199868,05"
4,2025-01-01,316903,231111021,Provisão de Eventos/Sinistros a Liquidar para ...,25535,25535

In [21]:
# Baixei todos os arquivos de operadoras inicialmente. No desafio 1.3 é necessario criar um .csv com colunas: 
# CNPJ , RazaoSocial , Trimestre , Ano , ValorDespesaTotal. Através da análise dos arquivos, notei que os arquivos de operadoras de plano de saúde são
# os que devem ser utilizados na análise, pois operadoras não hospitalares e operadoras acreditadas não possuem informações necessárias. Colunas das mesmas:
# ['Reg ANS', 'Operadora', 'Nivel_Acreditacao', 'Inicio_Validade', 'Fim_Validade', 'Prazo_validade', 'Resolucao_Normativa', 'Entidade_Acreditadora', 'Reacreditada', 'Data_da_Primeira_Acreditacao', 'Total de Anos de Acredita\x87Æo*']
# ['REGISTRO_OPERADORA', 'NM_OPERADORA', 'GR_MODALIDADE', 'ID_ESTABELECIMENTO_SAUDE', 'CD_CNPJ_ESTB_SAUDE', 'CD_CNES', 'NM_ESTABELECIMENTO_SAUDE', 'DE_CLAS_ESTB_SAUDE', 'DE_TIPO_PRESTADOR', 'LG_URGENCIA_EMERGENCIA', 'DE_TIPO_CONTRATO', 'DE_DISPONIBILIDADE', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'SG_UF', 'NM_REGIAO', 'DT_VINCULO_OPERADORA_INICIO', 'DT_VINCULO_OPERADORA_FIM', 'COMPETENCIA', 'DT_ATUALIZACAO']

In [22]:
operadoras = [
    os.path.join(DATA_DIR, f)
    for f in os.listdir(DATA_DIR)
    if f.startswith(("Relatorio")) and f.endswith(".csv")    
]

for operador in operadoras:
    print(f"Arquivo: {operador} ")
    le_exibe_colunas(operador)

Arquivo: ../data/Relatorio_cadop.csv
['REGISTRO_OPERADORA', 'CNPJ', 'Razao_Social', 'Nome_Fantasia', 'Modalidade', 'Logradouro', 'Numero', 'Complemento', 'Bairro', 'Cidade', 'UF', 'CEP', 'DDD', 'Telefone', 'Fax', 'Endereco_eletronico', 'Representante', 'Cargo_Representante', 'Regiao_de_Comercializacao', 'Data_Registro_ANS']
Arquivo: ../data/Relatorio_cadop_canceladas.csv
['REGISTRO_OPERADORA', 'CNPJ', 'Razao_Social', 'Nome_Fantasia', 'Modalidade', 'Logradouro', 'Numero', 'Complemento', 'Bairro', 'Cidade', 'UF', 'CEP', 'DDD', 'Telefone', 'Fax', 'Endereco_eletronico', 'Representante', 'Cargo_Representante', 'Regiao_de_Comercializacao', 'Data_Registro_ANS', 'Data_Descredenciamento', 'Motivo_do_Descredenciamento']

In [23]:


def trata_relatorio_cadop(filepath):
    df = pd.read_csv(filepath, sep=';', encoding='utf-8', dtype=str)
    
    print(f"Registros originais: {len(df)}")
    
   
    campos_obrigatorios = ['REGISTRO_OPERADORA', 'CNPJ', 'Razao_Social']
    for campo in campos_obrigatorios:
        df = df[df[campo].notna() & (df[campo].str.strip() != '')]
    print(f"Após remover NULLs em campos obrigatórios: {len(df)}")
    
    
    df['CNPJ'] = df['CNPJ'].str.replace(r'\D', '', regex=True) 
    df = df[df['CNPJ'].str.len() == 14]
    df = df[df['CNPJ'].apply(cnpj_tool.validate)]
    print(f"Após validar CNPJs: {len(df)}")
    
   
    df['REGISTRO_OPERADORA'] = pd.to_numeric(df['REGISTRO_OPERADORA'], errors='coerce')
    df = df[df['REGISTRO_OPERADORA'].notna()]
    df['REGISTRO_OPERADORA'] = df['REGISTRO_OPERADORA'].astype(int).astype(str)
    
    
    df['DDD'] = df['DDD'].str.replace(r'\D', '', regex=True)
    
    
    df['CEP'] = df['CEP'].str.replace(r'\D', '', regex=True)
    
    
    df['Regiao_de_Comercializacao'] = pd.to_numeric(df['Regiao_de_Comercializacao'], errors='coerce')
    df['Regiao_de_Comercializacao'] = df['Regiao_de_Comercializacao'].fillna(0).astype(int).astype(str)
    
    
   
    df['Data_Registro_ANS'] = pd.to_datetime(df['Data_Registro_ANS'], errors='coerce')
    registros_data_invalida = df['Data_Registro_ANS'].isna().sum()
    print(f"Registros com data inválida: {registros_data_invalida}")
    df = df[df['Data_Registro_ANS'].notna()]
    df['Data_Registro_ANS'] = df['Data_Registro_ANS'].dt.strftime('%Y-%m-%d')
    
    
   
    campos_texto = ['Razao_Social', 'Nome_Fantasia', 'Modalidade', 'Logradouro', 
                    'Numero', 'Complemento', 'Bairro', 'Cidade', 'Representante', 
                    'Cargo_Representante', 'Endereco_eletronico']
    for campo in campos_texto:
        if campo in df.columns:
            df[campo] = df[campo].fillna('').str.strip()
    
  
    df['UF'] = df['UF'].str.upper().str.strip()
    df = df[df['UF'].str.len() == 2]
    
    return df


cadop_path = os.path.join(DATA_DIR, 'Relatorio_cadop.csv')
df_cadop_tratado = trata_relatorio_cadop(cadop_path)


df_cadop_tratado.to_csv(cadop_path, index=False, sep=';', encoding='utf-8')
df_cadop_tratado.head()

Registros originais: 1110
Após remover NULLs em campos obrigatórios: 1110
Após validar CNPJs: 1110
Registros com data inválida: 0

,REGISTRO_OPERADORA,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,UF,CEP,DDD,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS
0,419761,19541931000125,18 DE JULHO ADMINISTRADORA DE BENEFÍCIOS LTDA,,Administradora de Benefícios,RUA CAPITÃO MEDEIROS DE REZENDE,274,,PRAÇA DA BANDEIRA,Além Paraíba,MG,36660000,32,34624649,NaN,contabilidade@cbnassessoria.com.br,LUIZ HENRIQUE MARENDINO GONÇALVES,SÓCIO ADMINISTRADOR,6,2015-05-19
1,421545,22869997000153,2B ODONTOLOGIA OPERADORA DE PLANOS ODONTOLÓGIC...,,Odontologia de Grupo,RUA CATÃO,128,SALA 126,VILA ROMANA,São Paulo,SP,05049000,11,34415852,NaN,labmarisol@gmail.com,MARISOL BECHELLI,SÓCIO ADMINISTRADORA,4,2019-06-13
2,421421,27452545000195,2CARE OPERADORA DE SAÚDE LTDA.,,Medicina de Grupo,RUA: BERNARDINO DE CAMPOS,230,1º ANDAR,CENTRO,Campinas,SP,13010151,19,37901224,NaN,ans.plano@hospitalcare.com.br,RODRIGO PINHO RIBEIRO,REPRESENTANTE,5,2018-10-09
3,418030,13138885000131,A.P.S. ADMINISTRADORA DE BENEFÍCOS LTDA.,A.P.S. SAÚDE.,Administradora de Benefícios,RUA VOLUNTÁRIOS DA PÁTRIA,2525,CONJUNTO 143 - SALA 01,SANTANA,São Paulo,SP,02401000,11,45223468,NaN,diretoria@apssaude.com.br,PERCÍVEL GAETA,SóCIO-ADMINISTRADOR E REPRESEN,4,2011-05-05
4,314668,17505793000101,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,ABERTTA SAÚDE,Autogestão,AV. BERNARDO MONTEIRO,831,"Subsolo, 2º andar e 3º andar",SANTA EFIGÊNIA,Belo Horizonte,MG,30150281,31,32484300,32484377,abertta.ans@arcelormittal.com.br,WERNER DUARTE DALLA,Diretor Presidente,4,1998-12-28

In [24]:
#gera df operadoras ativas / canceladas em 2025

In [25]:
dfs_operadoras = []
for operador in operadoras:
    df = pd.read_csv(operador, sep=';', encoding='utf-8')
    if 'Data_Descredenciamento' in df.columns:
        df['Data_Descredenciamento'] = pd.to_datetime(df['Data_Descredenciamento'], errors='coerce')
        df = df[df['Data_Descredenciamento'].isna() | (df['Data_Descredenciamento'].dt.year >= 2025)]
        dfs_operadoras.append(df)
    else:
        dfs_operadoras.append(df)

dfs_operadoras = pd.concat(dfs_operadoras, ignore_index=True)

dfs_operadoras.head()

,REGISTRO_OPERADORA,CNPJ,Razao_Social,Nome_Fantasia,Modalidade,Logradouro,Numero,Complemento,Bairro,Cidade,...,DDD,Telefone,Fax,Endereco_eletronico,Representante,Cargo_Representante,Regiao_de_Comercializacao,Data_Registro_ANS,Data_Descredenciamento,Motivo_do_Descredenciamento
0,419761,19541931000125,18 DE JULHO ADMINISTRADORA DE BENEFÍCIOS LTDA,NaN,Administradora de Benefícios,RUA CAPITÃO MEDEIROS DE REZENDE,274,NaN,PRAÇA DA BANDEIRA,Além Paraíba,...,32.0,34624649.0,NaN,contabilidade@cbnassessoria.com.br,LUIZ HENRIQUE MARENDINO GONÇALVES,SÓCIO ADMINISTRADOR,6.0,2015-05-19,NaT,NaN
1,421545,22869997000153,2B ODONTOLOGIA OPERADORA DE PLANOS ODONTOLÓGIC...,NaN,Odontologia de Grupo,RUA CATÃO,128,SALA 126,VILA ROMANA,São Paulo,...,11.0,34415852.0,NaN,labmarisol@gmail.com,MARISOL BECHELLI,SÓCIO ADMINISTRADORA,4.0,2019-06-13,NaT,NaN
2,421421,27452545000195,2CARE OPERADORA DE SAÚDE LTDA.,NaN,Medicina de Grupo,RUA: BERNARDINO DE CAMPOS,230,1º ANDAR,CENTRO,Campinas,...,19.0,37901224.0,NaN,ans.plano@hospitalcare.com.br,RODRIGO PINHO RIBEIRO,REPRESENTANTE,5.0,2018-10-09,NaT,NaN
3,418030,13138885000131,A.P.S. ADMINISTRADORA DE BENEFÍCOS LTDA.,A.P.S. SAÚDE.,Administradora de Benefícios,RUA VOLUNTÁRIOS DA PÁTRIA,2525,CONJUNTO 143 - SALA 01,SANTANA,São Paulo,...,11.0,45223468.0,NaN,diretoria@apssaude.com.br,PERCÍVEL GAETA,SóCIO-ADMINISTRADOR E REPRESEN,4.0,2011-05-05,NaT,NaN
4,314668,17505793000101,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,ABERTTA SAÚDE,Autogestão,AV. BERNARDO MONTEIRO,831,"Subsolo, 2º andar e 3º andar",SANTA EFIGÊNIA,Belo Horizonte,...,31.0,32484300.0,32484377.0,abertta.ans@arcelormittal.com.br,WERNER DUARTE DALLA,Diretor Presidente,4.0,1998-12-28,NaT,NaN

In [26]:
def gera_consolidado(df):
    df['Trimestre'] = df['DATA'].str.slice(5,7).map({'01':'1T','04':'2T','07':'3T'})
    df['Ano'] = df['DATA'].str.slice(0,4)
    df['VL_SALDO_FINAL'] = pd.to_numeric(df['VL_SALDO_FINAL'].str.replace(',', '.', regex=False), errors='coerce')
    df['VL_SALDO_INICIAL'] = pd.to_numeric(df['VL_SALDO_INICIAL'].str.replace(',', '.', regex=False), errors='coerce')
    df['ValorDespesas'] = (
    (df['VL_SALDO_FINAL'] - df['VL_SALDO_INICIAL']) * 100).round().astype('Int64')

    df_consolidado = df[['CNPJ', 'Razao_Social', 'Trimestre', 'Ano', 'ValorDespesas']]

    return df_consolidado

df_final = (
    df_eventos.merge(
    dfs_operadoras, 
    left_on='REG_ANS', 
    right_on='REGISTRO_OPERADORA', 
    how='inner'   
    )
    .pipe(gera_consolidado)
)


df_final.head(10)

,CNPJ,Razao_Social,Trimestre,Ano,ValorDespesas
0,42465310000121,TELOS - FUNDAÇÃO EMBRATEL DE SEGURIDADE SOCIAL,1T,2025,355806
1,42465310000121,TELOS - FUNDAÇÃO EMBRATEL DE SEGURIDADE SOCIAL,1T,2025,0
2,42465310000121,TELOS - FUNDAÇÃO EMBRATEL DE SEGURIDADE SOCIAL,1T,2025,-330099
3,42465310000121,TELOS - FUNDAÇÃO EMBRATEL DE SEGURIDADE SOCIAL,1T,2025,-330099
4,93507895000136,POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA,1T,2025,0
5,93507895000136,POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA,1T,2025,12467797
6,93507895000136,POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA,1T,2025,12487667
7,93507895000136,POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA,1T,2025,10222376
8,93507895000136,POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA,1T,2025,10222376
9,93507895000136,POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA,1T,2025,10222376

In [27]:
# FINAL TESTE 1 -> INICIO TESTE 2 
# Encontrados arquivos inconsistentes, com despesas negativas, zeradas, etc. 
# CNPJs duplicado também, trimestres aparentemente normais. 
# Solução: Corrigir. Já pegando o gancho do teste 2.1, vou validar valores 0/-,
# verificar trimestres e validar, corrigir cnpjs duplicados e com razoes sociais diferentes 
#  e aplicar uma validação de formato. Também verificar razão social não vazia.
#  TRADE-OFF DA VALIDAÇÃO: NO README.md

In [28]:
%pip install pandas validate-docbr

from validate_docbr import CNPJ

cnpj_tool = CNPJ()

def valida_valores_negativos_e_zeros(df):
    df_validado = df[(df['ValorDespesas'] > 0)]
    return df_validado

def valida_trimestres(df):
    trimestres_validos = {'1T', '2T', '3T'}
    df_validado = df[df['Trimestre'].isin(trimestres_validos)]
    return df_validado

def valida_cnpjs(df):
    
    #primeiro valida formato
    df['CNPJ'] = df['CNPJ'].astype(str)
    df = df[df['CNPJ'].apply(cnpj_tool.validate)]
    
    #valida duplicatas
    df = df.drop_duplicates(subset=['CNPJ', 'Trimestre'], keep='first')
    
    #valida razão social difernente para mesmo CNPJ
    df = df.sort_values(by=['CNPJ', 'Razao_Social'])
    df = df.drop_duplicates(subset=['CNPJ', 'Trimestre'], keep='first')
    
    #valida razao social vazia
    df = df[df['Razao_Social'].notna() & (df['Razao_Social'].str.strip() != '')]
    
    return df

df_final = (
    df_final.pipe(valida_valores_negativos_e_zeros)
            .pipe(valida_trimestres)
            .pipe(valida_cnpjs)
)

print(df_final.dtypes)
print(df_final.head())
csv_path = os.path.join(DATA_DIR, 'consolidados_despesas.csv')
zip_path = os.path.join(DATA_DIR, 'consolidados_despesas.zip')

df_final['ValorDespesas'] = df_final['ValorDespesas'].round(2)
df_final.to_csv(csv_path, index=False, sep=';', encoding='utf-8')

with open(csv_path, 'rb') as f_in, open(zip_path, 'wb') as f_out:
    f_out.write(f_in.read())

Requirement already satisfied: pandas in /media/ssd480/IntuitiveCare/.venv/lib/python3.11/site-packages (3.0.0)
Requirement already satisfied: validate-docbr in /media/ssd480/IntuitiveCare/.venv/lib/python3.11/site-packages (1.11.1)
Requirement already satisfied: numpy>=1.26.0 in /media/ssd480/IntuitiveCare/.venv/lib/python3.11/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /media/ssd480/IntuitiveCare/.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /media/ssd480/IntuitiveCare/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
CNPJ               str
Razao_Social       str
Trimestre          str
Ano                str
ValorDespesas    Int64
dtype: object
                  CNPJ                                       Razao_Social  \
53970   10219897000100  UNIMED OESTE DO PARÁ - COOPERATIVA DE TRABALHO...
103246  10219897000100  UNIMED OESTE DO PARÁ - COOPERATIVA DE TRABALHO...
117994  10219897000100  UNIMED OESTE DO PARÁ - COOPERATIVA DE TRABALHO...
13576   10364053000145  ODONTOLIVE OPERADORA DE PLANOS ODONTOLÓGICOS L...
78223   10364053000145  ODONTOLIVE OPERADORA DE PLANOS ODONTOLÓGICOS L...

       Trimestre   Ano  ValorDespesas
53970         1T  2025       44776509
103246        2T  2025       11813206
117994        3T  2025     2362858380
13576         1T  2025         258124
78223         2T  2025        2219128

In [29]:
df_operadoras_ativas = (
    pd.read_csv(os.path.join(DATA_DIR, 'Relatorio_cadop.csv'), sep=';', encoding='utf-8')   
)



def trata_cpnjs_duplicados(df1):
    df1['CNPJ'] = df1['CNPJ'].astype(str)
    
    df1['Data_Registro_ANS'] = pd.to_datetime(df1['Data_Registro_ANS'], errors='coerce')
    df_tratado = df1.sort_values(by=['Data_Registro_ANS']).drop_duplicates(subset=['CNPJ'], keep='last')   
    
    return df_tratado

df_operadoras_ativas_tratado = trata_cpnjs_duplicados(df_operadoras_ativas)

df_tratado = pd.merge(
    left=df_final, 
    right=df_operadoras_ativas_tratado, 
    on='CNPJ',
    how='inner' 
)

#lembrar trade-off 2.2

df_tratado = df_tratado.rename(columns={'Razao_Social_x': 'Razao_Social'})
df_tratado = df_tratado.rename(columns={'REGISTRO_OPERADORA': 'RegistroANS'})
df_tratado = df_tratado[['CNPJ', 'Razao_Social', 'Trimestre', 'Ano', 'ValorDespesas', 'RegistroANS', 'Modalidade', 'UF']]


df_tratado.head()

,CNPJ,Razao_Social,Trimestre,Ano,ValorDespesas,RegistroANS,Modalidade,UF
0,10219897000100,UNIMED OESTE DO PARÁ - COOPERATIVA DE TRABALHO...,1T,2025,44776509,362140,Cooperativa Médica,PA
1,10219897000100,UNIMED OESTE DO PARÁ - COOPERATIVA DE TRABALHO...,2T,2025,11813206,362140,Cooperativa Médica,PA
2,10219897000100,UNIMED OESTE DO PARÁ - COOPERATIVA DE TRABALHO...,3T,2025,2362858380,362140,Cooperativa Médica,PA
3,10364053000145,ODONTOLIVE OPERADORA DE PLANOS ODONTOLÓGICOS L...,1T,2025,258124,417831,Odontologia de Grupo,SP
4,10364053000145,ODONTOLIVE OPERADORA DE PLANOS ODONTOLÓGICOS L...,2T,2025,2219128,417831,Odontologia de Grupo,SP

In [30]:
#Agrupar por Razao Social e UF

In [31]:
df_agregado = df_tratado.groupby(['Razao_Social', 'UF'], as_index=False)['ValorDespesas'].sum()
df_agregado['ValorDespesas'] = df_agregado['ValorDespesas'].round(2)

for operadora in df_agregado['Razao_Social'].unique():
    df_operadora = df_tratado[df_tratado['Razao_Social'] == operadora]
    soma_despesas_por_operadora = df_operadora['ValorDespesas'].sum().round(2)
    print(f'Operadora: {operadora} - {soma_despesas_por_operadora}')


for uf in df_agregado['UF'].unique():
    df_uf = df_tratado[df_tratado['UF'] == uf]
    soma_despesas_por_uf = df_uf['ValorDespesas'].sum().round(2)
    print(f'UF: {uf} - {soma_despesas_por_uf}')


# tempo curto, mas para fazer a media é agrupar por trimestres, apos somar tudo de cada
# desvio padrao usa std()

print(df_agregado.shape)
df_agregado = df_agregado.sort_values(by='ValorDespesas', ascending=False)
df_agregado.head(20)

#colocar trade off 2.3: optei por sort_values pois o volume de dados não é significativo
# caso fosse, seguir abordagem dos chunks novamente. 

output_dir = os.path.join('..', 'data')
os.makedirs(output_dir, exist_ok=True)

csv_path = os.path.join(output_dir, 'despesas_agregadas.csv')
zip_path = os.path.join(output_dir, 'Teste_Gabriel_Diniz.zip')

df_agregado.to_csv(csv_path, index=False, sep=';', encoding='utf-8')

compression_opts = dict(method='zip', archive_name='despesas_agregadas.csv')
df_agregado.to_csv(zip_path, index=False, sep=';', encoding='utf-8', compression=compression_opts)

Operadora: 2CARE OPERADORA DE SAÚDE LTDA. - 6494071611
Operadora: ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMPREGADOS DA ARCELORMITTAL NO BRASIL - 10331612996
Operadora: AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL - 19786548
Operadora: ALICE OPERADORA LTDA. - 14868909996
Operadora: ALMA ODONTO OPERADORA DE PLANOS ODONTOLOGICOS LTDA - 23948929
Operadora: ALVORECER - ASSOCIAÇÃO DE SOCORROS MÚTUOS - 15349764568
Operadora: AMAZÔNIA PLANOS DE SAÚDE LTDA - 193469300
Operadora: AME VVIDA PLANOS DE SAUDE INTEGRADO LTDA. - 663331158
Operadora: AME-ASSISTÊNCIA MÉDICA A EMPRESAS LTDA - 246677642
Operadora: AMEPLAN ASSISTÊNCIA MÉDICA PLANEJADA LTDA - 485696524
Operadora: AMESC - ASSOCIAÇÃO MÉDICA ESPÍRITA CRISTÃ - 165424580
Operadora: AMHA SAUDE S/A - 5001092094
Operadora: AMHE MED ASSISTENCIA A SAUDE LTDA - EPP - 1744936315
Operadora: AMIL ASSISTÊNCIA MÉDICA INTERNACIONAL S.A. - 5280306718
Operadora: AMPARA ASSISTÊNCIA MÉDICA PARAÍSO LTDA - 1714477519
Operadora: AMPLA PLANOS DE SAUDE LTDA - 1725394847
Operadora: ANAFE SAUDE - 88721681
Operadora: ARL ADMINISTRADORA DE BENEFÍCIOS LTDA. - 284000
Operadora: ASSISTÊNCIA MÉDICA 12 DE OUTUBRO LTDA - 39274575
Operadora: ASSISTÊNCIA MÉDICA SÃO MIGUEL LTDA - 4527182705
Operadora: ASSOC DE ASSIST À SAÚDE DOS SERV DAS UNIV E INST FED, EST E/OU FAC PART EM PE - 129828217
Operadora: ASSOCIACAO CIVIL PRÓ-SAÚDE DOS SERVIDORES DA UNIVERSIDADE ESTADUAL DE PONTA GROSSA - 467458534
Operadora: ASSOCIACAO DE SAUDE HOLAMBRA - 395629981
Operadora: ASSOCIACAO DOS AUDITORES FISCAIS DA RECEITA ESTADUAL DE SAO PAULO - 8987244740
Operadora: ASSOCIACAO DOS PROFESSORES UNIVERSITÁRIOS DA BAHIA - 792488766
Operadora: ASSOCIACAO DOS SERVIDORES DA EMDAGRO - ASSEM - 202897901
Operadora: ASSOCIACAO POLICIAL DE ASSISTENCIA A SAUDE DE ITAPETININGA - 5230151
Operadora: ASSOCIAÇAO DOS FUNCIONARIOS PUBLICOS DO ESTADO DO RIO GRANDE DO SUL - 4492619331
Operadora: ASSOCIAÇAO UNISAUDE MARAU - 6081730
Operadora: ASSOCIAÇÃO ADVENTISTA NORTE BRASILEIRA DE PREVENÇÃO E ASSISTÊNCIA A SAÚDE - 5487971743
Operadora: ASSOCIAÇÃO BENEFICENTE CATÓLICA - 304711562
Operadora: ASSOCIAÇÃO BENEFICENTE DOS PROFESSORES PÚBLICOS ATIVOS E INATIVOS DO RIO DE JANEIRO - APPAI - 5601707281
Operadora: ASSOCIAÇÃO DA SANTA CASA SAÚDE DE RIBEIRÃO PRETO - 3970523046
Operadora: ASSOCIAÇÃO DE BENEFICÊNCIA E FILANTROPIA SÃO CRISTOVÃO - 17643860609
Operadora: ASSOCIAÇÃO DE SAÚDE DO VALE - 98309365
Operadora: ASSOCIAÇÃO DE SAÚDE DOS FORNECEDORES DE CANA DE PIRACICABA E REGIÃO - 45538683
Operadora: ASSOCIAÇÃO DE SAÚDE PORTUGUESA DE BENEFICÊNCIA - 4209839971
Operadora: ASSOCIAÇÃO DO FISCO DE ALAGOAS - 1221852077
Operadora: ASSOCIAÇÃO DO PLANO DE SAÚDE DA SANTA CASA DE MISERICÓRDIA DE ITABUNA - PLANSUL - 17544057
Operadora: ASSOCIAÇÃO DOS AUDITORES FISCAIS DA RECEITA ESTADUAL DO RIO DE JANEIRO - 799288060
Operadora: ASSOCIAÇÃO DOS EMPREGADOS DA COMPANHIA ESTADUAL DE HABITAÇÃO E OBRAS PÚBLICAS - ASSEC - 1622637
Operadora: ASSOCIAÇÃO DOS FISCAIS DE TRIBUTOS ESTADUAIS DO RS - AFISVEC - 123341236
Operadora: ASSOCIAÇÃO DOS SERVIDORES FISCAIS DO ESTADO DA BAHIA - 5933178291
Operadora: ASSOCIAÇÃO DOS SERVIDORES MUNICIPAIS, ESTADUAIS E FEDERAIS DO RIO DE JANEIRO - 457174989
Operadora: ASSOCIAÇÃO DOS SERVIDORES PÚBLICOS DA ADMINISTRAÇÃO DIRETA DO GOVERNO DO ESTADO DO PARÁ - ASPARÁ - 332352296
Operadora: ASSOCIAÇÃO DR. BARTHOLOMEU TACCHINI - 13554149746
Operadora: ASSOCIAÇÃO EVANGELICA BENEFICENTE DE LONDRINA - 5782263419
Operadora: ASSOCIAÇÃO FCA SAÚDE - 3044648458
Operadora: ASSOCIAÇÃO HOSPITAL SAÚDE DE VARGEM GRANDE DO SUL - 143701208
Operadora: ASSOCIAÇÃO MAIS SAÚDE SANTA CASA DE SÃO JOÃO DA BOA VISTA - 136558982
Operadora: ASSOCIAÇÃO MINEIRA DE ASSISTÊNCIA À SAÚDE DOS MEMBROS DO MINISTÉRIO PÚBLICO - 5398400184
Operadora: ASSOCIAÇÃO PADRE ALBINO SAÚDE - 63899006
Operadora: ASSOCIAÇÃO PADRE PIO PLANOS DE SAÚDE - 2192504
Operadora: ASSOCIAÇÃO PARANAENSE DE ASSISTÊNCIA À SAUDE DOS MEMBROS DO MINISTERIO PUBLICO DO PARANÁ - 1000393662
Operadora: ASSOCIAÇÃO PETROBRAS DE SAÚDE - APS - 1134910996
Operadora: ASSOCIAÇÃO PLANO DE SAÚDE SANTA CASA DE VALINHOS - 867528447
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTENCIA A SAUDE DE BOTUCATU - 75043444
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTENCIA À SAUDE DE SAO JOAO DA BOA VISTA - 277657912
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTÊNCIA À SAÚDE - 616743547
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTÊNCIA À SAÚDE DE ARAÇATUBA (APAS) - 587516119
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTÊNCIA À SAÚDE DE BARRETOS - 178431871
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTÊNCIA À SAÚDE DE JAÚ - 4946234
Operadora: ASSOCIAÇÃO POLICIAL DE ASSISTÊNCIA À SAÚDE DE RIBEIRÃO PRETO (APAS) - 781274834
Operadora: ASSOCIAÇÃO SANTA CASA CLÍNICAS DE BIRIGUI - 817774168
Operadora: ASSOCIAÇÃO SANTA CASA SAÚDE DE ARAÇATUBA - 53200366
Operadora: ASSOCIAÇÃO SANTA CASA SAÚDE DE SÃO JOSÉ DOS CAMPOS - 220208064
Operadora: ASSOCIAÇÃO SANTA SAÚDE - 72802432
Operadora: ASSOCIAÇÃO SAÚDE RURAL ALEGRETE - 570675
Operadora: ASSOCIAÇÃO SAÚDE SÃO JOSÉ - 34796650
Operadora: ASSOCIAÇÃO SERVIÇOS ODONTOLÓGICOS DA INDÚSTRIA DE MINAS GERAIS - ODONTOINDUSTRIA - 136700968
Operadora: ASSOCIAÇÃO SÃO FRANCISCO VIDA - 3291203324
Operadora: ASSOCIAÇÃO SÃO LUIZ SAÚDE - 1382166049
Operadora: ASSOCIAÇÃO UNIVIDA SANTA RITA DO PASSA QUATRO - 344201
Operadora: ATITUDE SAÚDE ASSISTÊNCIA MEDICA LTDA - 440036792
Operadora: ATÍVIA SERVIÇOS DE SAÚDE S/A - 557634390
Operadora: AURORA SAÚDE LTDA - 731903545
Operadora: AUSTACLINICAS ASSISTÊNCIA MÉDICA E HOSPITALAR LTDA - 1608064016
Operadora: BEMSTAR ASSISTENCIA MEDICA LTDA - 7188478
Operadora: BENEFICENCIA CAMILIANA DO SUL - 6881842467
Operadora: BENEFICENCIA SOCIAL BOM SAMARITANO - 177619840
Operadora: BEST SENIOR OPERADORA DE SAÚDE LTDA - 1325341982
Operadora: BIORAL SISTEMA ODONTOLÓGICO LTDA. - 3378105
Operadora: BLUZZ SAÚDE S/A - 42437953
Operadora: BRADESCO SAÚDE - OPERADORA DE PLANOS  S/A - 101470909
Operadora: BRADESCO SAÚDE S.A. - 24870959250
Operadora: BRASIL ODONTO OPERADORA DE PLANOS ODONTOLÓGICOS LTDA - 26115280
Operadora: BRASILDENTAL OPERADORA DE PLANOS ODONTOLÓGICOS S.A. - 1815257437
Operadora: CAIXA ASSISTENCIAL E BENEFICENTE DOS FUNCIONÁRIOS DA ACARESC - 128046992
Operadora: CAIXA BENEFICENTE DOS FUNCIONARIOS DO BANCO DO ESTADO DE SÃO PAULO - 291742082
Operadora: CAIXA BENEFICENTE DOS FUNCIONÁRIOS DO GRUPO IGUAÇU - 179908489
Operadora: CAIXA DE ASSISTENCIA A SAUDE DA UNIVERSIDADE - 13211664
Operadora: CAIXA DE ASSISTÊNCIA AOS MEMBROS DA DEFENSORIA PÚBLICA DO ESTADO DO RIO DE JANEIRO - 53647
Operadora: CAIXA DE ASSISTÊNCIA DOS EMPREGADOS DA SANEAGO - 2243000264
Operadora: CAIXA DE ASSISTÊNCIA DOS EMPREGADOS DO BANEB - 514699146
Operadora: CAIXA DE ASSISTÊNCIA DOS EMPREGADOS DO BANESE - 1226217846
Operadora: CAIXA DE ASSISTÊNCIA DOS EMPREGADOS DO SETOR PÚBLICO DO ESTADO DE GOIÁS - CAEME - 182432502
Operadora: CAIXA DE ASSISTÊNCIA DOS EMPREGADOS DO SISTEMA FINANCEIRO BANESTES - 4033961099
Operadora: CAIXA DE ASSISTÊNCIA DOS FUNCIONÁRIOS DO BANCO DO BRASIL - 411178366173
Operadora: CAIXA DE ASSISTÊNCIA DOS MAGISTRADOS DE PERNAMBUCO - 2291609937
Operadora: CAIXA DE ASSISTÊNCIA DOS SERVIDORES FAZENDÁRIOS ESTADUAIS - 41753154
Operadora: CAIXA DE ASSISTÊNCIA À SAÚDE - CABERJ - 62391985
Operadora: CAIXA DE ASSISTÊNCIA À SAÚDE DO SINDICATO DOS FUNCIONÁRIOS INTEGRANTES DO GRUPO OCUPACIONAL ADMINISTRAÇÃO TRIBUTÁRIA DO ESTADO DE PERNAMBUCO - 1450517197
Operadora: CAIXA DE ASSISTÊNCIA À SAÚDE DOS TRABALHADORES NAS INDÚSTRIAS METALÚRGICAS, MECÂNICAS E DO MATERIAL ELÉTRICO DE BRUSQUE - 605455641
Operadora: CAIXA DE PREVIDÊNCIA E ASSISTÊNCIA DOS SERVIDORES DA FUNDAÇÃO NACIONAL DE SAÚDE - CAPESESP - 7305427715
Operadora: CAIXA SEGURADORA ESPECIALIZADA EM SAÚDE S/A - 70183884
Operadora: CAMIM OPERADORA DE PLANO DE SAÚDE LTDA - 108412027
Operadora: CARING SAÚDE ASSISTÊNCIA MÉDICA LTDA. - 11914507
Operadora: CEAM BRASIL - PLANOS DE SAÚDE LTDA - 13173861
Operadora: CEMIG SAÚDE - 28519053202
Operadora: CENTRAL OPERADORA DE PLANOS DE SAÚDE NORTE-NORDESTE LTDA - 477608
Operadora: CENTRO TRASMONTANO DE SAO PAULO - 20607856672
Operadora: CIRCULO OPERARIO CAXIENSE - 14035215644
Operadora: CLINIPAM CLINICA PARANAENSE DE ASSISTENCIA MEDICA LTDA - 18924591180
Operadora: CLÍNICA SÃO GABRIEL S/S LTDA - 4841014
Operadora: COMSEDER - COOPERATIVA DE ASSISTÊNCIA MÉDICA DOS SERVIDORES DA SUPLAN E DO DER LTDA - 226469433
Operadora: CONFERÊNCIA SÃO JOSÉ DO AVAÍ - 17200406
Operadora: COOPERATIVA CENTRAL UNIMED DE COOPERATIVAS DE ASSISTÊNCIA À SAÚDE DO RIO GRANDE DO SUL LTDA. - 3423216
Operadora: COOPERATIVA DE TRABALHO MEDICO DE ARAGUAÍNA - UNIMED ARAGUAÍNA - 37913349
Operadora: COOPERATIVA DE TRABALHO MEDICO REGIÃO DO PLANALTO SERRANO - 2388170411
Operadora: COOPERATIVA DE TRABALHO MÉDICO DE POUSO ALEGRE - 8262461892
Operadora: COOPERATIVA DE TRABALHO MÉDICO DO PLANALTO NORTE DE SANTA CATARINA LTDA - 31752709
Operadora: COOPERATIVA DE TRABALHO ODONTOLOGICO - UNIODONTO ITAJUBÁ - 238419645
Operadora: COOPERATIVA DOS USUÁRIOS DE SERVIÇOS DE SAÚDE DO VALE DO RIO DOS SINOS LTDA - 528527
Operadora: CROWN ODONTOLOGIA DE GRUPO LTDA - 53394232
Operadora: DENTAL CENTER LTDA - 120761197
Operadora: DENTAL UNI - COOPERATIVA ODONTOLÓGICA - 4497831399
Operadora: DESBAN - FUNDAÇÃO BDMG DE SEGURIDADE SOCIAL - 6638189
Operadora: DONA SAÚDE CLINICAS LTDA - 4380242
Operadora: ECONOMUS INSTITUTO DE SEGURIDADE SOCIAL - 3850973570
Operadora: ELETROS SAÚDE - ASSOCIAÇÃO DE ASSISTÊNCIA À SAÚDE - 2484945181
Operadora: ELOSAÚDE - ASSOCIAÇÃO DE ASSISTÊNCIA À SAÚDE - 2499163204
Operadora: ESMALE ASSISTENCIA INTERNACIONAL DE SAUDE LTDA. - 1879662836
Operadora: EVO SAUDE ASSISTENCIA MEDICA LTDA - 8726422
Operadora: EXCELÊNCIA PLANO DE SAÚDE S/A - 8799829
Operadora: FEDERAÇÃO DAS SOCIEDADES COOPERATIVAS DE TRABALHO MÉDICO DO ACRE, AMAPÁ, AMAZONAS, PARÁ, RONDONIA E RORAIMA - 1205000226
Operadora: FUNDACAO LEONOR DE BARROS CAMARGO - 15888788
Operadora: FUNDAÇAO COMPESA DE PREVIDENCIA E ASSISTENCIA - COMPESAPREV - 13796024
Operadora: FUNDAÇÃO CELESC DE SEGURIDADE SOCIAL - CELOS - 3514978877
Operadora: FUNDAÇÃO CESP - 16367600
Operadora: FUNDAÇÃO CHESF DE ASSISTÊNCIA E SEGURIDADE SOCIAL - 6741394089
Operadora: FUNDAÇÃO COPEL DE PREVIDÊNCIA E ASSISTÊNCIA SOCIAL - 17207277
Operadora: FUNDAÇÃO DE ASSISTÊNCIA À SAÚDE DA ASSOCIAÇÃO DO MINISTÉRIO PÚBLICO DO RIO GRANDE DO SUL - 1289231270
Operadora: FUNDAÇÃO DE SEGURIDADE SOCIAL DA ARCELORMITTAL BRASIL - FUNSSEST - 4565196191
Operadora: FUNDAÇÃO FIAT SAÚDE E BEM ESTAR - 3665739802
Operadora: FUNDAÇÃO FILANTRÓPICA E BENEFICENTE DE SAÚDE ARNALDO GAVAZZA FILHO - 2051960621
Operadora: FUNDAÇÃO LIBERTAS DE SEGURIDADE SOCIAL - 9593826
Operadora: FUNDAÇÃO PLAMHUV - PLANO MÉDICO HOSPITALAR DOS HOSPITAIS UNIDOS DE VIÇOSA - 328051821
Operadora: FUNDAÇÃO SANEPAR DE ASSISTÊNCIA SOCIAL - 7827811755
Operadora: FUNDAÇÃO SAÚDE ITAÚ - 60624163974
Operadora: FUNDAÇÃO SÃO FRANCISCO XAVIER - 923969758
Operadora: FUNDO DE ASSISTÊNCIA MÉDICO-HOSPITALAR DO MINISTÉRIO PÚBLICO - 193081733
Operadora: G & M ASSESSORIA MEDICA EMPRESARIAL LTDA - 2251835
Operadora: GARANTIA DE SAÚDE LTDA - 4419567081
Operadora: GOCARE PLANOS DE SAUDE LTDA - 4024509698
Operadora: GRUPO HOSPITALAR DO RIO DE JANEIRO LTDA - 108778346391
Operadora: HAPVIDA ASSISTENCIA MEDICA S.A. - 1989489474
Operadora: HEALTH-MED SISTEMA DE SAUDE LTDA - 117536315
Operadora: HOSPITAL CESAR LEITE - 1752421
Operadora: HOSPITAL DE CARIDADE SÃO VICENTE DE PAULO - 70729308
Operadora: HOSPITAL DE PRONTOCLINICA LTDA. - 845421664
Operadora: HSMED SAUDE LTDA - 218643206
Operadora: HUMANA SAÚDE LTDA. - 10574711987
Operadora: INFINITY SAÚDE SUPLEMENTAR LTDA - 3835250
Operadora: INNOVA PLANO DE SAUDE LTDA - 128706353
Operadora: INSTITUIÇÃO BENEFICENTE CEL MASSOT - IBCM - 59322007
Operadora: INTEGRA ASSISTENCIA MEDICA SA - 4243521
Operadora: INTERCLINICAS PLANO VIDA USA OPERADORA DE SAUDE LTDA - 1256455
Operadora: INTERMEDICI PIRACICABA ASSISTENCIA MEDICA LTDA - 1059862200
Operadora: IRMANDADE DA SANTA CASA DE MISERICORDIA DE LIMEIRA - 2261097294
Operadora: IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE PASSOS - 1346342209
Operadora: IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE PIRACICABA - 4184670056
Operadora: IRMANDADE DA SANTA CASA DE MISERICÓRDIA DE RIO CLARO - 3177632073
Operadora: IRMANDADE DA SANTA CASA DE MISERICÓRDIA E MATERNIDADE DONA ZILDA SALVAGNI - 788759855
Operadora: IRMANDADE DE MISERICORDIA DE PORTO FERREIRA - 15398974
Operadora: IRMANDADE DE MISERICÓRDIA DO HOSPITAL DA SANTA CASA DE MONTE ALTO - 611841063
Operadora: IRMANDADE SANTA CASA DE MISERICÓRDIA DE MARINGÁ - 7382215173
Operadora: KLINI PLANOS DE SAÚDE LTDA - 7617297599
Operadora: LEVE SAUDE OPERADORA DE PLANOS DE SAUDE S.A - 43432239
Operadora: LIVRI OPERADORA DE PLANO DE SAÚDE LTDA - 6358368
Operadora: LUMINAR SAÚDE - ASSOCIAÇÃO DE ASSISTÊNCIA À SAÚDE - 2687799104
Operadora: MAIS SAUDE S/A - 53930114
Operadora: MATÃO CLINICAS & AMHMA SAÚDE LTDA - 13361897
Operadora: MEDGOLD ASSISTENCIA MEDICA LTDA - ME - 417147326
Operadora: MEDHEALTH PLANOS DE SAÚDE LTDA - 1943030
Operadora: MEDISERVICE OPERADORA DE PLANOS DE SAÚDE S.A. - 6221270735
Operadora: METRUS INSTITUTO DE SEGURIDADE SOCIAL - 67561803
Operadora: MÚTUA DOS MAGISTRADOS DO ESTADO DO RIO DE JANEIRO - 672777122
Operadora: NOTRE DAME INTERMÉDICA MINAS GERAIS SAÚDE S.A. - 249399447
Operadora: NOTRE DAME INTERMÉDICA SAÚDE S.A. - 11333131066
Operadora: NOVA SAÚDE OPERADORA INTEGRADA DE SAÚDE LTDA - 3443076615
Operadora: ODILE SERVIÇOS DE SAÚDE LTDA. - 49017110
Operadora: ODONT-OPERADORA ODONTOLOGICA LTDA - 28710577
Operadora: ODONTO EMPRESAS CONVENIOS DENTARIOS LTDA. - 685316804
Operadora: ODONTO PRIME S/S LTDA - 30742885
Operadora: ODONTO SEG OPERADORA DE PLANOS ODONTOLOGICOS S.A. - 80531340
Operadora: ODONTOLIVE OPERADORA DE PLANOS ODONTOLÓGICOS LTDA. - 2560406
Operadora: ODONTOPREV S/A - 852264929
Operadora: OMINT SERVIÇOS DE SAÚDE S.A. - 1188143336
Operadora: ON MED ASSISTÊNCIA MÉDICA LTDA - 676541865
Operadora: OPERADORA DE PLANOS PRIVADOS DE SAÚDE - SANTA CASA SAÚDE LTDA - 2022538044
Operadora: OPLAN SAÚDE OPERADORA DE PLANO DE SAÚDE LTDA - 363696461
Operadora: PARANA ASSISTENCIA MEDICA LTDA - 19070156
Operadora: PASA - PLANO DE ASSISTENCIA A SAUDE DO APOSENTADO DA VALE - 12115727551
Operadora: PB ASSISTENCIA MEDICA EU LTDA - 1401924331
Operadora: PD BRASIL ASSISTENCIA ODONTOLOGICA LTDA - 194125550
Operadora: PERSONAL CARE OPERADORA DE SAÚDE SA - 227192812
Operadora: PESSOAL SAÚDE PLANOS DE ASSISTÊNCIA MÉDICA LTDA - 1244158672
Operadora: PLADISA PLANOS DE SAÚDE SA - 80877698
Operadora: PLAMED PLANO DE ASSISTENCIA MEDICA LTDA - 1252504563
Operadora: PLAMER PLANO MEDICO RESENDE LTDA - 773365841
Operadora: PLAMESC PLANOS DE SAÚDE LTDA - 8753865
Operadora: PLANO DE ASSISTÊNCIA MÉDICA MINEIRA LTDA - 141558654
Operadora: PLANO DE ASSISTÊNCIA ODONTOLÓGICA FAUCHARD LTDA. ME - 129278729
Operadora: PLANO DE SAÚDE DA SANTA CASA DE BRAGANÇA PAULISTA - 9004532546
Operadora: PLANO SIGMA SAÚDE LTDA - 43467393
Operadora: PLENUM ASSISTENCIA MEDICA  LTDA - 45954948
Operadora: PLURAL GESTÃO EM PLANOS DE SAÚDE LTDA - 32173776
Operadora: POLIMÉDICA SAÚDE SOCIEDADE SIMPLES LTDA - 12570783
Operadora: PORTOMED - PORTO SEGURO SERVIÇOS DE SAUDE LTDA - 77869446
Operadora: POSTAL SAÚDE CAIXA DE ASSISTÊNCIA E SAÚDE DOS EMPREGADOS DOS CORREIOS - 1322835979
Operadora: PRESERVE SAUDE ASSISTENCIA MEDICA LTDA - 121765761
Operadora: PREVIDENT ASSISTÊNCIA ODONTOLÓGICA S.A - 927967023
Operadora: PROMÉDICA - PROTEÇÃO MEDICA A EMPRESAS S.A. - 7303643446
Operadora: PRONTO SOCORRO CONDE DE MOREIRA LIMA - 274749314
Operadora: PRONTOCLINICA E HOSPITAIS SAO LUCAS S/A - 1354214889
Operadora: PRONTOMED PLANOS DE SAÚDE LTDA - 73618281
Operadora: QUALIDONTO - QUALIDADE EM ODONTOLOGIA LTDA - 101448259
Operadora: QV BENEFÍCIOS EM SAÚDE LTDA - 4367368
Operadora: R.M.I. OPERADORA DE SAÚDE INTEGRADA LTDA - 482131196
Operadora: REAL GRANDEZA - FUNDAÇÃO DE PREVIDÊNCIA E ASSISTÊNCIA SOCIAL - 6954800
Operadora: RIO DOCE SAÚDE - 841322625
Operadora: S.P.A SAUDE- SISTEMA DE PROMOÇÃO ASSISTENCIAL - 5429416596
Operadora: S1 OPERADORA DE PLANO DE SAÚDE LTDA - 190064636
Operadora: SAGRADA SAÚDE ASSISTÊNCIA MÉDICA LTDA - 1324659
Operadora: SALUSMED OPERADORA DE PLANOS DE SAUDE LTDA - 135339295
Operadora: SAME-SERVIÇO DE ASSISTÊNCIA MÉDICA EMPRESARIAL LTDA. - 34126849
Operadora: SAMEDIL SERVIÇOS DE ATENDIMENTO MÉDICO S/A - 34974239206
Operadora: SAMEL PLANO DE SAÚDE LTDA - 40427332
Operadora: SAMI ASSISTÊNCIA MÉDICA LTDA - 4369951388
Operadora: SAMIG - SERV. DE ASSISTENCIA MEDICA DA ILHA DO GOVERNADOR LTDA - 141775579
Operadora: SAMOC S.A. - SOCIEDADE ASSISTENCIAL MÉDICA E ODONTO CIRÚRGICA - 1566890261
Operadora: SANTA CASA DA MISERICÓRDIA DE SÃO JOÃO DEL REI - 3636679
Operadora: SANTA CASA DE MISERICORDIA DE SAO JOAQUIM DA BARRA - 1743426621
Operadora: SANTA CASA DE MISERICORDIA HOSPITAL SÃO VICENTE - 3127842
Operadora: SANTA CASA DE MISERICÓRDIA DE JUIZ DE FORA - 17400929
Operadora: SANTA CASA DE MISERICÓRDIA DE TUPÃ - 3134055
Operadora: SANTA CASA DE MISERICÓRDIA DE VOTUPORANGA - 1136895454
Operadora: SANTA CASA DE MISERICÓRDIA E ASILO DOS POBRES DE BATATAIS - 1064548
Operadora: SANTA CASA DE MISERICÓRDIA E BENEFICÊNCIA PORTUGUESA - 621729613
Operadora: SANTA CASA DE SAÚDE - SCS - 67606399
Operadora: SANTA HELENA ASSISTÊNCIA MÉDICA S/A. - 57265054
Operadora: SAUDE SALV ASSISTENCIA MEDICA LTDA - 486337
Operadora: SAUDIA ASSISTENCIA MÉDICA LTDA - 5650437
Operadora: SAÚDE BRASIL ASSISTÊNCIA MÉDICA LTDA. - 2027548523
Operadora: SD-M OPERADORA DE PLANOS DE SAUDE LTDA - 139846621
Operadora: SELECT OPERADORA DE PLANO DE SAUDE LTDA - 1311082107
Operadora: SERMED-SAÚDE LTDA. - 5612222211
Operadora: SERV  SOCIAL AUTÔNOMO DE ASSIST À SAÚDE DOS SERV PÚBLICOS E MILITARES DE GOIÁS - 62914480583
Operadora: SERVIÇO SOCIAL DA INDÚSTRIA DO PAPEL, PAPELÃO E CORTIÇA DO ESTADO DE SÃO PAULO - SEPACO - 15765428040
Operadora: SIM - CAIXA DE ASSISTÊNCIA À SAÚDE - 40249018
Operadora: SISTEMA TOTAL DE SAÚDE LTDA. - 267178374
Operadora: SMART CARE SISTEMAS MÉDICOS E ODONTOLÓGICOS LTDA. - 25040313
Operadora: SOBAM CENTRO MÉDICO HOSPITALAR S.A. - 128770377
Operadora: SOCIEDADE BENEFICENTE DEZOITO DE JULHO - 19123785
Operadora: SOCIEDADE PORTUGUESA DE BENEFICÊNCIA - 1051292654
Operadora: SOCIODONTO PLANO DE ASSISTÊNCIA ODONTOLÓGICA LTDA - 156861
Operadora: SORRIDEN CONVÊNIOS ODONTOLÓGICOS S.A. - 33388011
Operadora: SUL AMÉRICA ODONTOLÓGICO S/A - 3225097
Operadora: SUL DO PARÁ LTDA - 1049573451
Operadora: SULMED - ASSISTÊNCIA MÉDICA LTDA - 24304641
Operadora: SÃO LUCAS SAÚDE S/A - 15868017
Operadora: TELOS - FUNDAÇÃO EMBRATEL DE SEGURIDADE SOCIAL - 862863
Operadora: TEMPO MED PLANO DE SAUDE LTDA - 3861952936
Operadora: TOTAL ASSISTÊNCIA MÉDICA HOSPITALAR LTDA - 72309665
Operadora: TRINO - ALIANCA FILANTRÓPICA DE ASSISTÊNCIA E INTEGRAÇÃO PARA O DESENVOLVIMENTO DA SAUDE - 47344801
Operadora: UNIMED - COOPERATIVA DE SERVIÇOS DE SAÚDE DOS VALES DO TAQUARI E RIO PARDO LTDA. - 31240810730
Operadora: UNIMED ALFENAS COOPERATIVA DE TRABALHO MEDICO - 13613034
Operadora: UNIMED ALTA MOGIANA COOPERATIVA DE TRABALHO MÉDICO - 2000434868
Operadora: UNIMED ALTO DA SERRA - SOCIEDADE COOPERATIVA DE SERVIÇO MÉDICO LTDA. - 18545483
Operadora: UNIMED ALTO JACUÍ/RS - COOPERATIVA DE ASSISTÊNCIA À SAÚDE LTDA - 436991974
Operadora: UNIMED ALTO SÃO FRANCISCO COOPERATIVA DE TRABALHO MÉDICO - 12402977
Operadora: UNIMED AMPARO COOPERATIVA DE TRABALHO MÉDICO - 270918734
Operadora: UNIMED ANHANGUERA COOPERATIVA DE TRABALHO MÉDICO - 126476681
Operadora: UNIMED ANÁPOLIS COOPERATIVA DE TRABALHO MÉDICO. - 7241655284
Operadora: UNIMED APUCARANA COOPERATIVA DE TRABALHO MÉDICO - 51549298
Operadora: UNIMED ARAGUARI COOPERATIVA DE TRABALHO MÉDICO - 1919525953
Operadora: UNIMED ARAXÁ COOPERATIVA DE TRABALHO MÉDICO LTDA. - 4087525753
Operadora: UNIMED BARBACENA - COOPERATIVA DE TRABALHO MÉDICO LTDA - 316806620
Operadora: UNIMED BARRA DO GARÇAS - COOPERATIVA DE TRABALHO MÉDICO - 3075669639
Operadora: UNIMED BELO HORIZONTE COOPERATIVA DE TRABALHO MÉDICO - 1851165875
Operadora: UNIMED BLUMENAU - COOPERATIVA DE TRABALHO MEDICO - 259156854